name: CI
on:
  push:
    branches:
      - main
    tags:
      - '*'
  pull_request:
    branches:
      - main
jobs:
  test:
    name: Node.js ${{ matrix.node-version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version:
          - 24
          - 22
          - 20
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm test
  types:
    name: TypeScript ${{ matrix.typescript-version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        typescript-version:
          - 'latest'
          - '~5.8.0'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm install
      - run: npm install typescript@${{ matrix.typescript-version }}
      - run: npx tsc
  test-export:
    name: Test Module Export
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm install rollup rollup-plugin-dts
      - run: npx rollup index.d.ts -p rollup-plugin-dts -d temp
  link-checker:
    name: Link Checker
    uses: lycheeverse/lychee-action@v2
    with:
      # Check all markdown, html and reStructuredText files in repo (default)
      args: --base . --verbose --no-progress './**/*.md' './**/*.html' './**/*.rst'
      # Use json as output format (instead of markdown)
      format: json
      # Use different output file path
      output: /tmp/foo.txt
      # Use a custom GitHub token, which
      token: ${{ secrets.CUSTOM_TOKEN }}
      # Don't fail action on broken links
      fail: false
      # Run lychee in a different directory.
      # Note: This changes the lychee output directory as well.
      workingDirectory: website/subdir